ci: 添加 -w

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -16,9 +16,9 @@ jobs:
         with:
           version: latest
       - name: Build Backend
-        run:
+        run: |
           pnpm install
-          pnpm run build:server || (echo "Build failed, see logs below:" && cat ./packages/server/dist/build.log)
+          pnpm --workspace-root run build:server || (echo "Build failed, see logs below:" && cat ./packages/server/dist/build.log)
       - name: SCP Backend to Server
         run: |
           tar -czf server.tar.gz packages/server/dist
